### PR TITLE
WPF client

### PR DESCRIPTION
**Pull request by gmrukwa**
This branch contains whole WPF client for DiviK algorithm.

Resolves: #61, #58, #57, #53, #52, #47.

### CODE REVIEW

**Comment by gmrukwa** [comment]
@Sand3r- honestly, MainPageVm also should be tested - that's one of the purposes of using MVVM pattern. But I would leave it as it is, since it is one-time app. We will proceed with web client further on rather than this solution.

**Comment by Sand3r-** [comment]
Alrighty, feel free to merge then.

**Comment by gmrukwa** [comment]
[Prepare standalone DiviK software](https://trello.com/c/CPUL9yxs/63-prepare-standalone-divik-software)

**Comment by gmrukwa** [comment]
[Logging in matlab/cpp](https://trello.com/c/9VL91hXk/88-logging-in-matlab-cpp)

**Pull request merged**
